version: '3'

services:
  mysql-docker-container:
    container_name: mysql-docker-container
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    volumes:
      - /data/mysql
  spring-boot-jpa-app:
    container_name: spring-boot-jpa-app
    build:
      context: ./
      dockerfile: Dockerfile
    image: spring-boot-jpa-image:latest
    depends_on:
      - mysql-docker-container
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql-docker-container
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=test
      - DATABASE_PORT=3308
    volumes:
      - /data/spring-boot-app